remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Rahul Murthy
description: Some basic examples of client interfaces to a computer vision API. Updating for myself

author:
  name: Jeremy Howard
